name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t harshan536/react-app . 

      - name: Push Docker image
        run: docker push harshan536/react-app  
      
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu  # Your EC2 instance username
          key: ${{ secrets.SSH }}
          script: |
            sudo systemctl start docker
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-app
            docker stop $(docker ps -q) || true
            docker run -d --restart unless-stopped -p 80:80 ${{ secrets.DOCKER_USERNAME }}/react-app
