name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t harshan536/react-app . 

      - name: Push Docker image
        run: docker push harshan536/react-app
deploy:
  needs: build-and-push
  runs-on: self-hosted
  steps:
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull image from Docker Hub
      run: docker pull harshan536/react-app:latest 

    - name: Stop and remove existing container (if running)
      run: |
        docker stop affectionate_shannon || true
        docker rm affectionate_shannon || true

    - name: Run new Docker container
      run: docker run -d -p 5000:3000 --name affectionate_shannon harshan536/react-app

