name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t harshan536/react-app . 

      - name: Push Docker image
        run: docker push harshan536/react-app  
      
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }} 
          username: ubuntu 
          key: ${{ secrets.SSH_KEYS }}
          script: |
            sudo apt-get install -y docker.io 
            sudo systemctl start docker         
            sudo systemctl enable docker         
            docker pull harshan536/react-app
            docker stop $(docker ps -q) || true
            docker run -d -p 3000:3000 harshan536/react-app
